### PR TITLE
Updated for June

### PR DESCRIPTION
**Pull request by ghotihed**
- Updated meeting dates and Zoom details

### CODE REVIEW

**Comment by MatthewGreet** [comment]
Can't review if I'm not a reviewer.

**Comment by ghotihed** [comment]
> Can't review if I'm not a reviewer.

Well, that's true enough. Oops.

Although, it might have been possible for you to make yourself a reviewer. I don't really know whether that's possible. It should be fixed now.

**Review by mking90031-Jordan — COMMENTED** [review]
@ghotihed,

Are you aware book club & 2 Dice are on the same day?  Is that deliberate?

**Comment by ghotihed** [comment]
> Are you aware book club & 2 Dice are on the same day? Is that deliberate?

Yes, it's deliberate. As we've discussed previously, the gaming meetup is every 29 days, so the day rotates throughout the week and people who can't make it on some days get to attend on others. This means that it's going to coincide with other meetings, on occasion. For the time it coincides with a General Meeting, I'll probably jigger it a little so that skips that day, because of the timing conflict. But the book club doesn't conflict, time-wise, with the gaming.

**Review by MatthewGreet — APPROVED** [review]

**Pull request merged**
